spring:
  datasource:
    url: jdbc:h2:mem:turnstile;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console